title: SQL of the Day
description: A personal archive of weekly SQL practice problems.
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

collections_dir: .
collections:
  posts:
    output: true
    permalink: /:collection/:name
